### ISSUE TITLE
pf_dim 是什么意思呢？

### ISSUE THREAD

**Issue by cfy42584125** [jiangnanboy/intent_detection_and_slot_filling#2]
在Encoder和EncoderLayer中都有pf_dim这个参数，想问一下这个参数是什么意思？
是代表线性层维度吗

**Comment by jiangnanboy** [comment]
那个是前馈层，你可以看一下transformer结构





------------------ 原始邮件 ------------------
发件人: cfy42584125 ***@***.***&gt;
发送时间: 2021年7月7日 09:44
收件人: jiangnanboy/intent_detection_and_slot_filling ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[jiangnanboy/intent_detection_and_slot_filling] pf_dim 是什么意思呢？ (#2)





 
在Encoder和EncoderLayer中都有pf_dim这个参数，想问一下这个参数是什么意思？
